version = 0.1

[default]
[default.build]
[default.build.parameters]
parallel = true

[default.deploy]
[default.deploy.parameters]
stack_name = "nest-serverless"
s3_bucket = "your-deployment-artifacts-bucket"
s3_prefix = "nest-serverless"
region = "ap-northeast-1" # Change to your preferred region
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
  "VpcId=vpc-06d8f6eb8f945b72b",
  "PrivateSubnetIds=\"subnet-01b175c8a1a98ebf0,subnet-0de7e5cd892bf72bb\"",
  "DatabaseUrl=postgresql://postgres2:Lumia1520@database-2.cf8a068489ao.ap-northeast-1.rds.amazonaws.com:5432"
]

[default.sync]
[default.sync.parameters]
watch = true

[default.local_start_api]
[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda]
[default.local_start_lambda.parameters]
warm_containers = "EAGER"
